spring:
 profiles.active: local
 threads:
  virtual:
   enabled: true

---
spring:
 config.activate.on-profile: local
 datasource:
    username: postgres
    password: local_postgres
    url: jdbc:postgresql://localhost:5432/demo_seed_sm
    driver-class-name: org.postgresql.Driver	
 jpa:
    show-sql: true
    generate-ddl: true
    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
     ddl-auto: create
 threads:
  virtual:
   enabled: true     
jackson:
  serialization:
    write-dates-as-timestamps: false 